version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    command: -p 5432
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build:
      context: .
    env_file:
      - .env
    container_name: api
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ['cmd/app.sh']

volumes:
  pgdata:
